version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80"
    volumes:
      - .:/var/www/html
    links:
      - bancodedados
  bancodedados:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: dataDB
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  phpqa:
    image: jakzal/phpqa:php7.1-alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80"
    links:
      - "bancodedados:db"